[package]
name = "propolis"
version = "0.1.0"
authors = ["Patrick Mooney <pmooney@pfmooney.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
pico-args = "0.3"
bhyve_api = { path = "bhyve-api" }
aspace = { path = "util/aspace" }
