[package]
name = "propolis"
version = "0.1.0"
authors = ["Patrick Mooney <pmooney@pfmooney.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
libc = "0.2"
pico-args = "0.3"
bitflags = "1.2"
byteorder = "1"
lazy_static = "1.4"
num_enum = "0.5"
bhyve_api = { path = "bhyve-api" }
